INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000121', 'HINDUSTANI BANK', 'GOREGAON');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000276', 'HINDUSTANI BANK', 'MUMBAI');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000352', 'HINDUSTANI BANK', 'DELHI');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000987', 'HINDUSTANI BANK', 'SHIMLA');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000111', 'HINDUSTANI BANK', 'AMRITSAR');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000190', 'HINDUSTANI BANK', 'PATNA');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000789', 'HINDUSTANI BANK', 'NAVI MUMBAI');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000666', 'HINDUSTANI BANK', 'GOA');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000010', 'HINDUSTANI BANK', 'BENGALORE');
INSERT INTO `bms_pr`.`bank_info` (`IFSC_CODE`, `BANK_NAME`, `BRANCH_NAME`) VALUES ('HBB0000899', 'HINDUSTANI BANK', 'HYDERABAD');


SELECT * FROM bank_info;