CREATE DATABASE BMS_PR;

USE BMS_PR;

-- to show databses use the command (show databases;)


-- CUSTOMER INFO


CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR(10),
CUSTOMER_NAME VARCHAR(50),
DOB DATE,
GUARDIAN_NAME VARCHAR(50),
ADDRESS VARCHAR(30),
CONTACT_NO BIGINT(12),
EMAIL_ID VARCHAR(20),
GENDER VARCHAR(2),
MARITAL_STATUS VARCHAR(10),
IDENTIFICATION_TYPE VARCHAR(15),
ID_NO VARCHAR(20),
PRIMARY KEY(CUSTOMER_ID)
);

-- SHOW TABLES; (TO SHOW ALL THE TABLES)

-- SELECT * FROM CUSTOMER; ( TO DISPLAY TABLE STRUCTURE)

CREATE TABLE CUSTOMER_REEFERENCE(
CUSTOMER_ID VARCHAR(15),
REF_ACC_NAME VARCHAR(20),
REF_ACC_NO BIGINT(15),
REF_ACC_ADDRESS VARCHAR(25),
RELATION VARCHAR(20)
);


-- TO CREATE FOREIGN KEY
ALTER TABLE CUSTOMER_REEFERENCE
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

-- SHOW TABLES;

-- BANK INFO TABLE

CREATE TABLE BANK_INFO(
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(20),
BRANCH_NAME VARCHAR(20),
PRIMARY KEY(IFSC_CODE)
);


-- ACC INFO TABLE


CREATE TABLE ACC_INFO(
ACC_NO BIGINT(20),
CUSTOMER_ID VARCHAR(10),
ACC_TYPE VARCHAR(15),
REGISTRATION_DT DATE,
ACTIVATION_DT DATE,
IFSC_CODE VARCHAR(15),
INTEREST DECIMAL(4,4),
PRINCIPAL_AMT BIGINT(10),
PRIMARY KEY(ACC_NO)
);

ALTER TABLE ACC_INFO
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);



ALTER TABLE ACC_INFO
ADD FOREIGN KEY (IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE);










