INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C001', 'SUMUKH KUMAR', '261728190235', 'GOREGAON', 'BROTHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C002', 'HARSHITA PATEL', '362839029123', 'MUMBAI', 'SISTER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C003', 'BISWA KUMAR PRADHAN', '473829307351', 'DELHI', 'BROTHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C004', 'REKHA SHARMA', '543216789065', 'SHIMLA', 'MOTHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C005', 'SALMAN AKTHAR', '543212345678', 'AMRITSAR', 'FATHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C006', 'MANOJ GUPTA', '987654321234', 'PATNA', 'FATHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C007', 'BIKAS GORE', '787878654432', 'NAVI MUMBAI', 'FATHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C008', 'SIDDHI MANE', '654321234321', 'GOA', 'SISTER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C009', 'RAM KUMAR', '998007611231', 'BANGALORE', 'BROTHER');
INSERT INTO `bms_pr`.`customer_reeference` (`CUSTOMER_ID`, `REF_ACC_NAME`, `REF_ACC_NO`, `REF_ACC_ADDRESS`, `RELATION`) VALUES ('C010', 'ANUPAM SHAH', '334567890987', 'HYDERABAD', 'BROTHER');


SELECT * FROM customer_reeference;